export module Screen.ScreenName;

export enum class ScreenName {
    MAIN,
    SINGLE_PLAYER_MAIN,
    SINGLE_PLAYER_START,
    SINGLE_PLAYER_RANK,
    SINGLE_PLAYER_END,
    MULTI_PLAYER_MAIN,
    MULTI_PLAYER_START,
    MULTI_PLAYER_END,
    USERNAME_INPUT,
    SERVER_INPUT,
    EXIT
};
